### ISSUE TITLE
上下文、作用域

### ISSUE THREAD

**Issue by mrrs878** [Advanced-Frontend/Just-Now-QA#9]
如题，想问一下JavaScript中上下文和作用域的区别

**Comment by mrrs878** [comment]
我自己的理解作用域是静态的，只要代码写好后就一直存在并不再发生变化；上下文是动态的，函数执行完就被释放了

**Comment by yygmind** [comment]
一两句话说不清楚，可以看看我之前写的几篇文章

[理解JavaScript 中的执行上下文和执行栈](https://muyiy.cn/blog/1/1.1.html)
[深入浅出图解作用域链和闭包](https://muyiy.cn/blog/2/2.1.html)

**Comment by mrrs878** [comment]
3Q
